jwt_hardcode_secret.py
Reverts anhkhoa14592/semgrep-test-repository#83
=> Revert "Test: delete file"

VerificationController.java
Reverts anhkhoa14592/semgrep-test-repository#115
=> Revert "Update: fix send to slack when result too long - 2"

VerificationController.java
Reverts anhkhoa14592/semgrep-test-repository#116
=> Revert "Revert "Update: fix send to slack when result too long - 2""

xxe_autofix.java
Reverts anhkhoa14592/semgrep-test-repository#133
=> Revert "Revert "Update: comment line 136""

xxe_autofix.java
Reverts anhkhoa14592/semgrep-test-repository#134
=> Revert "Revert "Revert "Update: comment line 136"""

VerificationController.java, credential_leak.txt, cve-2024-23334.py, xxe_autofix.java
Reverts anhkhoa14592/semgrep-test-repository#137
=> Revert "Update: test"

VerificationController.java, credential_leak.txt, cve-2024-23334.py, xxe_autofix.java
Reverts anhkhoa14592/semgrep-test-repository#138
=> Revert "Revert "Update: test""

VerificationController.java, credential_leak.txt, cve-2024-23334.py, xxe_autofix.java
Reverts anhkhoa14592/semgrep-test-repository#139
=> Revert "Revert "Revert "Update: test"""

VerificationController.java, credential_leak.txt, cve-2024-23334.py, xxe_autofix.java
Reverts anhkhoa14592/semgrep-test-repository#140
=> Revert "Revert "Revert "Revert "Update: test""""

VerificationController.java, credential_leak.txt, cve-2024-23334.py, xxe_autofix.java
Reverts anhkhoa14592/semgrep-test-repository#141
=> Revert "Revert "Revert "Revert "Revert "Update: test"""""

VerificationController.java, credential_leak.txt, cve-2024-23334.py, xxe_autofix.java
Reverts anhkhoa14592/semgrep-test-repository#142
=> Revert "Revert "Revert "Revert "Revert "Revert "Update: test""""""

cve-2024-23334.py
Reverts anhkhoa14592/semgrep-test-repository#145
=> Revert "Revert: change SHA image kafka and parser"

cve-2024-23334.py
Reverts anhkhoa14592/semgrep-test-repository#147
=> Revert "Revert "Revert "Revert: change SHA image kafka and parser"""

cve-2024-23334.py
Reverts anhkhoa14592/semgrep-test-repository#148
=> Revert "Revert "Revert "Revert "Revert: change SHA image kafka and parser""""

cve-2024-23334.py
Reverts anhkhoa14592/semgrep-test-repository#149
=> Revert "Revert "Revert "Revert "Revert "Revert: change SHA image kafka and parser"""""

credential_leak.txt
Reverts anhkhoa14592/semgrep-test-repository#159
=> Revert "Revert "Revert "Update: add fingerprint attribute"""

xxe_autofix_test.java
Reverts anhkhoa14592/semgrep-test-repository#179
=> Revert "Revert "Revert "Revert "Revert "Update: add attribute for llm context v2, rm functions parseKafka and…"""""

xxe_autofix_test.java
Reverts anhkhoa14592/semgrep-test-repository#180
=> Revert "Revert "Revert "Revert "Revert "Revert "Update: add attribute for llm context v2, rm functions parseKafka and…""""""

xxe_autofix_test.java
Reverts anhkhoa14592/semgrep-test-repository#181
=> Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update: add attribute for llm context v2, rm functions parseKafka and…"""""""

xxe_autofix_test.java
Reverts anhkhoa14592/semgrep-test-repository#182
=> Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update: add attribute for llm context v2, rm functions parseKafka and…""""""""
